description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: actions/setup-node@v3
      with:
        cache: pnpm
        node-version: '20'
    - uses: pnpm/action-setup@v4
      with:
        version: 9
    - run: pnpm install"
      shell: bash
  using: composite
