name: Dependabot auto-merge
on: pull_request_review

jobs:
  dependabot:
    if: github.actor == 'dependabot[bot]' && review.state == 'approved'
    runs-on:
      steps:
        - run: gh pr merge --auto
